[2023-09-22T23:49:51.198+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.create_users_table manual__2023-09-22T23:49:50.430743+00:00 [queued]>
[2023-09-22T23:49:51.210+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_multi_table.create_users_table manual__2023-09-22T23:49:50.430743+00:00 [queued]>
[2023-09-22T23:49:51.211+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-22T23:49:51.212+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-22T23:49:51.212+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-22T23:49:51.227+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_users_table> on 2023-09-22 23:49:50.430743+00:00
[2023-09-22T23:49:51.231+0000] {standard_task_runner.py:55} INFO - Started process 801 to run task
[2023-09-22T23:49:51.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_multi_table', 'create_users_table', 'manual__2023-09-22T23:49:50.430743+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/crt_tbls_trs_data.py', '--cfg-path', '/tmp/tmplqw2vr3j']
[2023-09-22T23:49:51.235+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask create_users_table
[2023-09-22T23:49:51.288+0000] {task_command.py:376} INFO - Running <TaskInstance: create_multi_table.create_users_table manual__2023-09-22T23:49:50.430743+00:00 [running]> on host 411713a30e55
[2023-09-22T23:49:51.346+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_multi_table
AIRFLOW_CTX_TASK_ID=create_users_table
AIRFLOW_CTX_EXECUTION_DATE=2023-09-22T23:49:50.430743+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-22T23:49:50.430743+00:00
[2023-09-22T23:49:51.356+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-22T23:49:51.360+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users(
                first_name TEXT NULL,
                last_name TEXT NULL,
                email TEXT NULL,
                street_number SMALLINT NULL,
                street_name TEXT NULL,
                surburb TEXT NULL,
                post_code INTEGER NULL,
                state TEXT NULL,
                country TEXT NULL
            );
        , parameters: None
[2023-09-22T23:49:51.361+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2023-09-22T23:49:51.372+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=create_multi_table, task_id=create_users_table, execution_date=20230922T234950, start_date=20230922T234951, end_date=20230922T234951
[2023-09-22T23:49:51.407+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-09-22T23:49:51.431+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
