[2023-09-20T12:49:34.842+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_ML_customerchurn.create_table manual__2023-09-20T12:49:32.815156+00:00 [queued]>
[2023-09-20T12:49:34.866+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: create_ML_customerchurn.create_table manual__2023-09-20T12:49:32.815156+00:00 [queued]>
[2023-09-20T12:49:34.868+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-09-20T12:49:34.871+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-09-20T12:49:34.872+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-09-20T12:49:34.920+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2023-09-20 12:49:32.815156+00:00
[2023-09-20T12:49:34.958+0000] {standard_task_runner.py:55} INFO - Started process 16256 to run task
[2023-09-20T12:49:34.966+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_ML_customerchurn', 'create_table', 'manual__2023-09-20T12:49:32.815156+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/copy_db.py', '--cfg-path', '/tmp/tmpjdxiqhn3']
[2023-09-20T12:49:34.969+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask create_table
[2023-09-20T12:49:35.117+0000] {task_command.py:376} INFO - Running <TaskInstance: create_ML_customerchurn.create_table manual__2023-09-20T12:49:32.815156+00:00 [running]> on host 411713a30e55
[2023-09-20T12:49:35.308+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_ML_customerchurn
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-09-20T12:49:32.815156+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-20T12:49:32.815156+00:00
[2023-09-20T12:49:35.336+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-09-20T12:49:35.344+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS machine_learning_customerchurn(
                state TEXT NULL,
                account_length INTEGER NULL,
                area_code INTEGER NULL,
                phone_number TEXT NULL,
                international_plan TEXT NULL,
                voice_mail_plan TEXT NULL,
                number_vmail_messages INTEGER NULL,
                total_day_minutes FLOAT NULL, 
                total_day_calls INTEGER NULL,
                total_day_charge FLOAT NULL,
                total_eve_minutes FLOAT NULL,
                total_eve_calls INTEGER NULL,
                total_eve_charge FLOAT NULL,
                total_night_minutes FLOAT NULL,
                total_night_calls INTEGER NULL,
                total_night_charge FLOAT NULL,
                total_intl_minutes FLOAT NULL,
                total_intl_calls INTEGER NULL,
                total_intl_charge FLOAT NULL,
                customer_service_calls INTEGER NULL,
                churn BOOLEAN NULL
            );
        , parameters: None
[2023-09-20T12:49:35.346+0000] {postgres.py:96} INFO - NOTICE:  relation "machine_learning_customerchurn" already exists, skipping

[2023-09-20T12:49:35.367+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=create_ML_customerchurn, task_id=create_table, execution_date=20230920T124932, start_date=20230920T124934, end_date=20230920T124935
[2023-09-20T12:49:35.424+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-09-20T12:49:35.463+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
